### ISSUE TITLE
Listener is not closing cleanly due to LoopReads task encountering exception

### ISSUE THREAD

**Issue by avanaur** [nemtech/nem2-sdk-csharp#4]
Hi,

It seems that closing the listener is causing the background task LoopReads to encounter exception.

```
[13/09/2018 1:29:30 PM Error] The active test run was aborted. Reason: Unhandled Exception: System.OperationCanceledException: Aborted ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request. ---> System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, Boolean throwOnPrematureClosure)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   --- End of inner exception stack trace ---
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TWebSocketReceiveResultGetter,TWebSocketReceiveResult](Memory`1 payloadBuffer, CancellationToken cancellationToken, TWebSocketReceiveResultGetter resultGetter)
   at io.nem2.sdk.Infrastructure.Listeners.Listener.ReadSocket() in C:\Users\Tyrone\workspace\nem2-sdk-csharp\src\nem2-sdk\src\Infrastructure\Listeners\Listener.cs:line 140
   at io.nem2.sdk.Infrastructure.Listeners.Listener.LoopRead() in C:\Users\Tyrone\workspace\nem2-sdk-csharp\src\nem2-sdk\src\Infrastructure\Listeners\Listener.cs:line 122
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

To replicate
```
        [TestMethod, Timeout(20000)]
        public async Task CloseListener()
        {
            var listener = new Listener("localhost");

            await listener.Open();

            listener.Close();
        }
```

I am using io.nem2.sdk/0.8.1

**Comment by kodty** [comment]
Fixed on develop branch. waiting on merge

**Comment by avanaur** [comment]
I tried the develop branch. However, it seems the same issue arise when creating a new Listener  once an old one was opened and closed.

```
        [TestMethod, Timeout(20000)]
        public async Task CloseListenerTwice()
        {
            var listener = new Listener("localhost");

            await listener.Open();
            listener.AggregateBondedAdded(Address.CreateFromRawAddress("SDB5DP6VGVNPSQJYEC2X3QIWKAFJ3DCMNQCIF6OA"));

            listener.Close();
            
            var listener2 = new Listener("privatetest1.xpxsirius.io");

            await listener.Open();

        }
```
